"""
A local-navigation training environment that runs INSIDE the real
PyBullet maze -- real rectangular corridor/room walls, the real Lidar2D
sensor, and the real Drone velocity controller -- instead of the abstract
circular-obstacle environment in env_fast.py.

This directly fixes the honest gap flagged in review: a policy trained
only against circular obstacles in an open field has never seen a wall,
let alone a corridor. Training here means the policy's entire experience
is generated by raycasting against the actual maze geometry it will be
deployed into.

Trade-off, stated plainly: real PyBullet physics stepping is far slower
than the abstract environment's pure-numpy math (roughly two orders of
magnitude), so this supports far fewer training episodes in the same
wall-clock budget. Treat a policy trained here as a proof-of-concept that
the approach transfers to real geometry, not as a fully converged
solution -- see README for exactly how much training went into the
shipped checkpoint and what more training would likely buy you.

Episode design: drone starts at one room center (with jitter), must reach
another room center within a bounded distance (so early training sees a
tractable single-corridor-or-junction hop, not a full end-to-end maze
traverse -- the latter is a much harder, longer-horizon problem better
suited to hierarchical RL or the classical frontier planner + local RL
combination this project already uses in main.py).
"""

import numpy as np
import pybullet as p
import pybullet_data

from maze_env import config as C
from maze_env import config as C
from maze_env.maze_generator import MazeGenerator
from maze_env.drone import Drone
from maze_env.sensors import Lidar2D

NUM_RAYS = 16
LIDAR_MAX_RANGE = 3.5      # same as env_maze.py / rl_controller.py (was 4.0: train/deploy mismatch)
MAX_FORWARD_SPEED = 1.2    # same as env_maze.py / rl_controller.py (was 1.0)
MAX_TURN_RATE = 2.0
GOAL_RADIUS = 0.4
COLLISION_MARGIN = 0.28  # drone visual/collision radius (~0.16) + safety pad
CRUISE_ALT = C.CRUISE_ALT


class RealMazeNavEnv:
    obs_dim = NUM_RAYS + 3
    act_dim = 2

    def __init__(self, grid_n=3, maze_seed=0, max_steps=60, max_goal_dist=5.0,
                 rl_step_dt=0.15, seed=None, split="train"):
        self.split = split
        self.grid_n = grid_n
        self.max_steps = max_steps
        self.max_goal_dist = max_goal_dist
        self.rl_step_dt = rl_step_dt
        self.phys_dt = 1.0 / 240.0
        self.ticks_per_step = max(1, int(round(rl_step_dt / self.phys_dt)))
        self.rng = np.random.default_rng(seed)

        self.client = p.connect(p.DIRECT)
        p.setAdditionalSearchPath(pybullet_data.getDataPath())
        p.setGravity(0, 0, -9.81)
        p.setTimeStep(self.phys_dt)

        self.lidar = Lidar2D(num_rays=180, max_range=LIDAR_MAX_RANGE)
        self.maze = None
        self.drone = None
        self.rebuild_maze(maze_seed)

    def rebuild_maze(self, maze_seed):
        """Tear down and rebuild the whole world with a new maze layout --
        call this every so often during training (not every episode, since
        it's comparatively expensive) to keep the policy from overfitting
        to one specific wall configuration."""
        p.resetSimulation()
        p.setGravity(0, 0, -9.81)
        self.maze = MazeGenerator(grid_n=self.grid_n, seed=maze_seed)
        while self.maze.layout_split() != self.split:      # split by LAYOUT, never by seed
            maze_seed += 1
            self.maze = MazeGenerator(grid_n=self.grid_n, seed=maze_seed)
        while self.maze.layout_split() != self.split:       # only layouts from this env's split
            maze_seed += 1
            self.maze = MazeGenerator(grid_n=self.grid_n, seed=maze_seed)
        self.maze.build_in_pybullet(self.client)
        self.room_centers = self.maze.all_room_centers()
        self.drone = Drone(start_xyz=[self.room_centers[0][0], self.room_centers[0][1], CRUISE_ALT])
        self.drone.reset_controller_state()

    def _sample_start_goal(self):
        for _ in range(30):
            start_room = self.room_centers[self.rng.integers(len(self.room_centers))]
            goal_room = self.room_centers[self.rng.integers(len(self.room_centers))]
            start = start_room + self.rng.uniform(-0.5, 0.5, 2)
            goal = goal_room + self.rng.uniform(-0.5, 0.5, 2)
            d = np.linalg.norm(goal - start)
            if 1.0 < d < self.max_goal_dist:
                return start, goal
        return start, goal  # fall back to last sample if we didn't find a great pair

    def reset(self):
        start, goal = self._sample_start_goal()
        self.goal = goal
        yaw0 = self.rng.uniform(-np.pi, np.pi)
        quat = p.getQuaternionFromEuler([0, 0, yaw0])
        p.resetBasePositionAndOrientation(self.drone.body, [start[0], start[1], CRUISE_ALT], quat)
        p.resetBaseVelocity(self.drone.body, [0, 0, 0], [0, 0, 0])
        self.drone.target_yaw = yaw0
        self.drone.reset_controller_state()
        self.steps = 0
        self.prev_dist = np.linalg.norm(self.goal - start)
        obs, *_ = self._obs()
        return obs

    def _obs(self):
        pos, yaw, *_ = self.drone.get_ground_truth_pose()   # (was `pos, yaw, _, _ =`: crashed, the drone returns 9 values)
        _, ranges = self.lidar.scan(pos, yaw)
        idx = np.linspace(0, len(ranges) - 1, NUM_RAYS).astype(int)
        lidar_obs = np.clip(ranges[idx], 0, LIDAR_MAX_RANGE) / LIDAR_MAX_RANGE

        to_goal = self.goal - pos[:2]
        dist = np.linalg.norm(to_goal)
        bearing = np.arctan2(to_goal[1], to_goal[0]) - yaw
        goal_obs = np.array([np.clip(dist / (self.grid_n * self.maze.cell_pitch * 1.5), 0, 1),   # same normalisation as env_maze.py
                              np.sin(bearing), np.cos(bearing)])
        return np.concatenate([lidar_obs, goal_obs]).astype(np.float32), pos, yaw, dist, ranges[idx]

    def step(self, action):
        speed = float(np.clip(action[0], 0, 1)) * MAX_FORWARD_SPEED
        turn = float(np.clip(action[1], -1, 1)) * MAX_TURN_RATE

        for _ in range(self.ticks_per_step):
            pos, yaw, *_ = self.drone.get_ground_truth_pose()   # (was `pos, yaw, _, _ =`: crashed, the drone returns 9 values)
            vx = speed * np.cos(yaw)
            vy = speed * np.sin(yaw)
            vz_cmd = 2.0 * (CRUISE_ALT - pos[2])  # hold cruise altitude
            self.drone.command_velocity(vx, vy, vz_cmd, turn)
            p.stepSimulation()

        self.steps += 1
        obs, pos, yaw, dist, lidar_sample = self._obs()

        progress_reward = (self.prev_dist - dist) * 5.0
        self.prev_dist = dist
        step_penalty = -0.02

        # real contact-based collision check -- an actual PyBullet contact
        # event against a wall body (excluding floor/ceiling, which the
        # drone shouldn't touch in normal operation anyway, but excluding
        # them explicitly keeps this robust regardless)
        contacts = p.getContactPoints(bodyA=self.drone.body) or ()
        wall_contact = any(c[2] != self.maze.floor_id and c[2] != self.maze.ceiling_id
                            for c in contacts)
        out_of_bounds = pos[2] < 0.3 or pos[2] > 2.2
        collided = wall_contact or out_of_bounds or \
            float(np.min(lidar_sample)) * LIDAR_MAX_RANGE < COLLISION_MARGIN
        reached_goal = dist < GOAL_RADIUS

        reward = progress_reward + step_penalty
        done = False
        if collided:
            reward -= 5.0
            done = True
        elif reached_goal:
            reward += 10.0
            done = True
        elif self.steps >= self.max_steps:
            done = True

        return obs, reward, done, {"collided": collided, "reached_goal": reached_goal}

    def close(self):
        p.disconnect(self.client)
